### PR TITLE
Update readme

### PR DESCRIPTION
**Pull request by eddiezane**
My pr does things.

```release-note
New release note
```

Check it out.

### CODE REVIEW

**Comment by eddiezane** [comment]
/release-note-edit

```release-note
This is the new release note
```

Stuff

**Comment by eddiezane** [comment]
/release-note-edit

```release-note
This is the new note
```
Stuff

**Comment by eddiezane** [comment]
/release-note-edit

```release-note
This is the new note
```
Stuff

**Comment by eddiezane** [comment]
/release-note-edit

```release-note
This is the new note
```
Stuff

**Comment by eddiezane** [comment]
/release-note-edit

```release-note
This is the new note
```
Stuff

**Comment by eddiezane** [comment]
/release-note-edit

```release-note
NONE
```
Stuff

**Comment by eddiezane** [comment]
/release-note-edit

```release-note
I added new things
```
Stuff

**Comment by eddiezane** [comment]
/release-note-edit

```release-note
New release note
```

Stuff

**Comment by kikisdeliveryservice** [comment]
/release-note-edit

kirsten's test

**Comment by kikisdeliveryservice** [comment]
ok that didnt work

/release-note-edit

edit note

Stuff

**Comment by eddiezane** [comment]
/release-note-edit

Missing a block

**Comment by eddiezane** [comment]
/release-note-edit

```release-note
This is a multiline release note
Of different

Things 2123
```

Stuff

**Comment by kikisdeliveryservice** [comment]
Would it be possible to error:

 /release-note-edit must be used with a release note block:
 
```release-note
New release note
```

For people like me who will absolutely get it wrong?

Edit: Wait... that formatted itself into a release note block. Foiled.

**Comment by kikisdeliveryservice** [comment]
/release-note-edit

What am i doing? The wrong thing.

**Comment by kikisdeliveryservice** [comment]
Other than my comment above, which very well may not be possible, this def solves the how do i update the release note easily without being the author problem 👍

**Comment by eddiezane** [comment]
/release-note-edit

```release-note
New release note
```

Stuff

**Pull request closed without merging**
